<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Nexus.Domain\Nexus.Domain.csproj" />
    <ProjectReference Include="..\Nexus.Core\Nexus.Core.csproj" />
    <ProjectReference Include="..\Nexus.Graph\Nexus.Graph.csproj" />
    <ProjectReference Include="..\Nexus.Risk\Nexus.Risk.csproj" />
    <ProjectReference Include="..\Nexus.Application\Nexus.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
